### ISSUE TITLE
WHY IS THE API DOWN?!!! 

### ISSUE THREAD

**Issue by PallavBS** [brawlstarsAPI/api#1]
Hey can I get whitelisted
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Edit by API Author**
The following reply describes why the API is down and the conversation below refers to that topic as well.

**Comment by kranemax** [comment]
Hello, I'm from the API Team and would like to apologise that the API is currently having issues retrieving data from the gameservers. We have therefore **blocked all requests** so our error logs don't get spammed.

This will get fixed ASAP. We will update on this thread once it is fixed. For notifications, please subscribe to the thread.

**Comment by kranemax** [comment]
For now, I suggest webscraping https://www.brawlstats.io as it is a good site that doesn't deserve ad revenue.

**Comment by SharpBit** [comment]
Savage xD

**Comment by kranemax** [comment]
Hello @SharpBit, I'm not really sure what you were referring to. Everything I've said is true.

**Comment by PallavBS** [comment]
I appreciate the speedy replys, looking forward to using this api.

**Comment by ravener** [comment]
Lol y scrape brawlstats.io

**Comment by SharpBit** [comment]
@freetnt5852  because it doesn't deserve the ad revenue.

**Comment by kranemax** [comment]
I'll be working on the API over the weekend. Might not have all the features that it used to have (blame supercell) but I'll be working on it. Let me know which features you guys want best and I'll ensure it gets up this weekend! Thanks for the support! 💪

**Comment by 0arm** [comment]
@kranemax what language is the API written in and what can we do to get involved in its development?

**Comment by kranemax** [comment]
Hello @kyb3r, it'd be better to create a separate issue for that for organisation sake.

EDIT: I've just created a `CONTRIBUTING.md ` that answers all your questions.

**Comment by kranemax** [comment]
Currently Planned to come by next Monday:
- Player stats (Trophies, highest, boss best time, robo rumble, tag, name, badge) 
- Basic band info (name, tag, badge)
- List of brawler **names**

**Comment by SharpBit** [comment]
Hey, @kranemax, you said suggest some stuff for the API. So here are my suggestions.
```
1. Player info, brawlers, brawler info, player info, etc
2. For each brawler the player has, include info about their brawler like trophies, pb, etc
3. Assets (PNG files) of stuff like profile icon(highest brawler), and each brawler in the game
4. Events (current and upcoming)
5. Their band info, return a "band object", with info of the band (name, description, location, type, etc)
6. In band info: maybe a list of members objects that do #1, 2, and 5
```
I know this is a lot to ask by the weekend, but if you can't do all this by the weekend, I am willing to wait more. If any of this list is restricted by supercell, just tell me and I will understand.

**Comment by kranemax** [comment]
@SharpBit, thank you so much for the support!

For number 6, it might require another requests to the /bands endpoint. I'll try my best to include all the other endpoints.

I'm working on mainly the /players endpoint by the weekend. Hopefully I'll get some basic information in /bands but I can't confirm for sure.

I have forked a repository, [brawlstarsAPI/bs assets](https://www.github.com/brawlstarsAPI/bs-assets) and will likely be using that as my point of assets, and provide links to the image files from there.

**Comment by kranemax** [comment]
I'm dropping some information below about things I've confirmed in the new API Design:

There might be Authorization keys, in bearer. Not confirmed.

Standard format as follows
```json
{
    "status": {
        "error": false,
        "code": 200,
        "message": "OK"
    },
    "data": {}
}
```
As always, this is subject to minor changes but this is the mindset I have with the API design. Endpoints would be the same as current, `/players `, `/bands ` all with `/api` in the base url.

**Comment by Quantumlyy** [comment]
Maybe add a brawler endpoint for a player to get a single brawlers stats for that player to not overflow the result. Also is there is discord or slack for the API?

**Comment by Harmiox** [comment]
Looks like you guys are having fun.

**Comment by kranemax** [comment]
I intend on creating one, but not when the API isn't working. I might be working on using querystrings to filter the result so you don't get a super huge JSON object that you aren't using. It's on the to do list, but not in the high priority.

**Comment by SharpBit** [comment]
Hey, you probably know this already, but the profile icons are `bs-assets/images/thumbnails/high/player_icon_id-or-name.png` right? Just making sure

**Comment by kranemax** [comment]
It should be, yes. The links will be given by the API in the response so you can use them directly so don't worry about that.

**Comment by umbresp** [comment]
whew this blew up

**Comment by SharpBit** [comment]
Cool, keep it up! I would help but I don't fullfil the first 2 requirements in contributing.md
Edit: oh and the sanic one
Maybe ask kyber or something

**Comment by umbresp** [comment]
what if you fulfill half the requirements and someone else fulfills half the requirements, can we count as one person?

**Comment by kranemax** [comment]
Hey @SharpBit, I'd love to see you help out. These messages are much more fit for our [discord server](https://discord.gg/r3rbf9U) which I'll do a much more proper announcement about once I actually get the API going.

I'm not currently looking out for contributors and people to help, and therefore I've not immediately accepted your request. The first 2 pointers are the most important and are therefore the first 2 themselves, so I hope you'd learn them and DM me hopefully soon on discord. Till then, enjoy!

**Comment by kranemax** [comment]
Hey @umbresp, I'm looking to share the source code with as little people as possible, and people I personally would quite trust. Therefore that'd not count as two people :(

**Comment by umbresp** [comment]
@kyb3r teach me how to decrypt supercell’s packets pls thanks senpai

**Comment by kranemax** [comment]
We have added a bit of statistics to `/players/:tag`, and will add more as the time goes on. Hopefully we'll clear the list of `SharpBit`'s suggested features by the end of the weekend.

**Comment by SharpBit** [comment]
Ok, thanks! Also you linked the discord server to this thread.

Edit: never mind, I didn't refresh the page

**Comment by kranemax** [comment]
The link is [right here](https://discord.gg/r3rbf9U). See you there!

**Comment by Dorian349** [comment]
@kranemax Is it possible to contact you on Discord?

**Comment by SharpBit** [comment]
@NairodTV Hey there, there's a great brawl stars API online at https://brawlapi.cf/api

Join the discord to get your API key: https://discord.me/BrawlAPI
