### ISSUE TITLE
/api/events returns 404 not found

### ISSUE THREAD

**Issue by umbresp** [brawlstarsAPI/api#2]
Pretty self-explanatory title.
```
{  
    "status":{  
        "error":true,
        "message":"Invalid Page, maybe you meant /api",
        "code":404
    }
}
```
(/api/bands/{tag} returns 404 as well.)

**Comment by SharpBit** [comment]
As he stated already, events and band endpoints aren't ready yet.

**Comment by kranemax** [comment]
I'm currently working on this. Expect a week or so of eta

**Comment by kranemax** [comment]
Endpoint created
